# 公共配置文件
spring:
  application:
    name: nero-api-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis 配置
  redis:
    database: 0
    host: 182.92.155.77
    port: 6379
    timeout: 5000
    password: 123456
  # session 配置
  session:
    # 分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.155.77:3306/neroapi
    username: neroapi
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置

cos:
  client:
    accessKey: AKIDkRxJTXQVdbMJDuQnz2CIHB0iLpBMPL57
    secretKey: 53tdHqHbr13yoZP9mFctGXihkDZkhbVV
    region: ap-beijing
    bucket: file--upload-1322447072
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    urlPrefix: https://file--upload.oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tBXUbdSV14LT7wfYqUC
    accessKeySecret: RYMwdaMwpjkoH2mNEjaMDtKKCEqLTl
    bucketName: file--upload
    fileHost: files

nero:
  gateway:
    host: http://localhost:8090


dubbo:
  application:
    name: nero-api-admin-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://182.92.155.77:8848
